# Generated by Django 3.2.9 on 2021-12-01 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0002_localsparty_tickets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='name_party',
        ),
    ]
