# Generated by Django 3.2.8 on 2021-12-05 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('party', '0003_remove_tickets_name_party'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataSales', models.DateTimeField(blank=True)),
                ('countTicket', models.IntegerField()),
                ('price_Ticket', models.IntegerField()),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tickets_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.tickets')),
            ],
        ),
    ]
